# Generated by Django 5.2.7 on 2025-10-02 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Автошкола', 'verbose_name_plural': 'Автошколы'},
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.TextField(verbose_name='Название школы'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('age', models.TextField(verbose_name='Возраст')),
                ('school_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driving_school.school')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
