# Generated by Django 5.2.7 on 2025-10-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0002_alter_school_options_alter_school_name_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.TextField(verbose_name='Номер')),
                ('model', models.TextField(verbose_name='Модель')),
                ('car_make', models.TextField(verbose_name='Марка')),
                ('vehicle_category', models.TextField(verbose_name='Категория транспортного средства')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driving_school.course'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('age', models.TextField(verbose_name='Возраст')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driving_school.car')),
                ('school_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driving_school.school')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
    ]
