# Generated by Django 5.2.7 on 2025-10-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0003_car_course_student_school_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to='students', verbose_name='Изображение'),
        ),
    ]
