# Generated by Django 5.2.7 on 2025-10-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0004_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='picture',
            field=models.ImageField(null=True, upload_to='instructors', verbose_name='Изображение'),
        ),
    ]
