# Generated by Django 5.2.7 on 2025-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0007_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
