# Generated by Django 5.2.7 on 2025-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0010_remove_userprofile_otp_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_see_page2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
