# Generated by Django 5.2.7 on 2025-12-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0011_userprofile_can_see_page2_userprofile_totp_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_see_page2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totp_key',
        ),
    ]
