# Generated by Django 5.2.7 on 2025-12-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0012_remove_userprofile_can_see_page2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
